version: '3.1'
services:
  db:
    image: mysql
    container_name: database
    environment:
      MYSQL_ROOT_PASSWORD: root
    ports:
    - '3306:3306'
    volumes:
    - mentorship_data:/var/lib/mysql

volumes:
  mentorship_data:

